### ISSUE TITLE
[BUG] Home screen frozen with blogs activated

### ISSUE THREAD

**Issue by loganewhaley** [nmelhado/league-page#101]
**Describe the bug**
If blogs are enabled, you can't navigate to any of the tabs (trades/waivers, open league info drop down, etc.) on the home screen. The tabs show up and you can click on them, but the pages will not load. There is a workaround to where if you click on a tab (i.e. matchups) and refresh the page it'll load and the drop downs will work properly, but you can't physically get to any of the pages from the home screen.

**Your League ID**
784484879164362752

**To Reproduce**
1. Go to home page (draftdaydynasty.vercel.app)
2. Attempt to click on any of the above tabs (matchups, trades & waivers, league info, etc.)
3. See error

**Expected behavior**
When I click on the matchups tab from home page, I expect the matchups page to load. If I click on league info from home page, I expect a drop-down menu.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacBook Pro
 - Browser Chrome
 - Version 96.0.4664.131

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro Max
 - OS: iOS 15.1

**Comment by nmelhado** [comment]
Make sure that all fields are filled out for the blog post (title, author, type, body). Omitting one will cause errors. If that doesn't resolve the issue, let me know.

**Comment by nmelhado** [comment]
Just to follow up, there was a bug that was trying to display draft blogs. I fixed that in a separate pr. Let me know if that might have been the cause, and I'll close this out!

**Comment by nmelhado** [comment]
I'm closing this for now. If neither of the above help, feel free to reopen and I'll investigate further.

**Comment by BravesVolsUU** [comment]
Ahh, my mistake for just now getting back around to this. Work got hectic this week, but finally have some down time.

The issue is still persisting for me (I have 2 different pages for my leagues and I opened up the issue on the wrong one... this is the page I'm having the issue on). Just double-checked Contentful, and there are no drafts and everything is assigned an author, type, title and body.

**Comment by nmelhado** [comment]
I'll re-open this then. Would you mind posting screenshots of the your contentful setup? The error on that page is `Post-afe91257.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'title')`, so it's having some kind of an issue with the title of one of your posts. It's hard to debug this since I'm not hooked up to your contentful, but I might figure it out with some screenshots.

In particular a copy of paste of the JSON from your post content model:
https://app.contentful.com/spaces/<your_space>/content_types/blog_post/preview 
i.e:
```
{
  "name": "Blog Post",
  "description": "",
  "displayField": "title",
  "fields": [
    {
      "id": "title",
      "name": "Title",
      "type": "Symbol",
      "localized": false,
      "required": true,
      "validations": [],
      "disabled": false,
      "omitted": false
    },
    {
      "id": "type",
      "name": "Type",
      "type": "Symbol",
      "localized": false,
      "required": true,
      "validations": [
        {
          "in": [
            "Weekly Preview",
            "Weekly Recap",
            "PSA",
            "General",
            "League Change Proposal",
            "Trash Talk"
          ]
        }
      ],
      "disabled": false,
      "omitted": false
    },
    {
      "id": "featured",
      "name": "Featured",
      "type": "Boolean",
      "localized": false,
      "required": false,
      "validations": [],
      "defaultValue": {
        "en-US": true
      },
      "disabled": false,
      "omitted": false
    },
    {
      "id": "body",
      "name": "Body",
      "type": "RichText",
      "localized": false,
      "required": true,
      "validations": [
        {
          "nodes": {}
        }
      ],
      "disabled": false,
      "omitted": false
    },
    {
      "id": "author",
      "name": "Author",
      "type": "Symbol",
      "localized": false,
      "required": true,
      "validations": [],
      "disabled": false,
      "omitted": false
    }
  ],
  "sys": {
    "space": {
      "sys": {
        "type": "Link",
        "linkType": "Space",
        "id": "zzzzzzzzz"
      }
    },
    "id": "blog_post",
    "type": "ContentType",
    "createdAt": "2021-09-08T23:24:28.476Z",
    "updatedAt": "2021-09-10T20:22:29.983Z",
    "environment": {
      "sys": {
        "id": "master",
        "type": "Link",
        "linkType": "Environment"
      }
    },
    "publishedVersion": 5,
    "publishedAt": "2021-09-10T20:22:29.983Z",
    "firstPublishedAt": "2021-09-08T23:24:28.735Z",
    "createdBy": {
      "sys": {
        "type": "Link",
        "linkType": "User",
        "id": "zzzzzzz"
      }
    },
    "updatedBy": {
      "sys": {
        "type": "Link",
        "linkType": "User",
        "id": "zzzzzzz"
      }
    },
    "publishedCounter": 3,
    "version": 6,
    "publishedBy": {
      "sys": {
        "type": "Link",
        "linkType": "User",
        "id": "yyyyyyy"
      }
    }
  }
}
```

As well as a screenshot of the posts you've made?

**Comment by BravesVolsUU** [comment]
Made some changes to Contentful settings but still nothing yet. I can tell some of my settings differ from the one you sent, so I think that might have something to do with it. I've attached the 3 blog posts I've made (yes, the last one I've made was in week 6, 2022 goal is to be more consistent with those posts haha)

<img width="1382" alt="Screen Shot 2022-01-13 at 3 48 01 PM" src="https://user-images.githubusercontent.com/88356004/149414359-575350a0-e2ef-4659-929a-8669938dd8b9.png">
<img width="1391" alt="Screen Shot 2022-01-13 at 3 47 47 PM" src="https://user-images.githubusercontent.com/88356004/149414365-afd4b581-b8e9-4185-aba3-d2520609125c.png">
<img width="1379" alt="Screen Shot 2022-01-13 at 3 47 09 PM" src="https://user-images.githubusercontent.com/88356004/149414370-a662957c-d0a2-461a-8ccf-4a04be2e8446.png">

{
  "name": "Blog",
  "description": "",
  "displayField": "title",
  "fields": [
    {
      "id": "title",
      "name": "Title",
      "type": "Symbol",
      "localized": false,
      "required": true,
      "validations": [],
      "disabled": false,
      "omitted": false
    },
    {
      "id": "type",
      "name": "Type",
      "type": "Symbol",
      "localized": false,
      "required": true,
      "validations": [
        {
          "in": [
            "Weekly Preview",
            "Weekly Recap",
            "PSA",
            "General",
            "League Change Proposal",
            "Trash Talk"
          ]
        }
      ],
      "disabled": false,
      "omitted": false
    },
    {
      "id": "featured",
      "name": "Featured",
      "type": "Boolean",
      "localized": false,
      "required": false,
      "validations": [],
      "disabled": false,
      "omitted": false
    },
    {
      "id": "body",
      "name": "Body",
      "type": "RichText",
      "localized": false,
      "required": true,
      "validations": [
        {
          "enabledMarks": [
            "bold",
            "italic",
            "underline",
            "code"
          ],
          "message": "Only bold, italic, underline, and code marks are allowed"
        },
        {
          "enabledNodeTypes": [
            "heading-1",
            "heading-2",
            "heading-3",
            "heading-4",
            "heading-5",
            "heading-6",
            "ordered-list",
            "unordered-list",
            "hr",
            "blockquote",
            "embedded-entry-block",
            "embedded-asset-block",
            "hyperlink",
            "entry-hyperlink",
            "asset-hyperlink",
            "embedded-entry-inline"
          ],
          "message": "Only heading 1, heading 2, heading 3, heading 4, heading 5, heading 6, ordered list, unordered list, horizontal rule, quote, block entry, asset, link to Url, link to entry, link to asset, and inline entry nodes are allowed"
        },
        {
          "nodes": {}
        }
      ],
      "disabled": false,
      "omitted": false
    },
    {
      "id": "author",
      "name": "Author",
      "type": "Symbol",
      "localized": false,
      "required": true,
      "validations": [],
      "disabled": false,
      "omitted": false
    }
  ],
  "sys": {
    "space": {
      "sys": {
        "type": "Link",
        "linkType": "Space",
        "id": "b2ldzzl4lvug"
      }
    },
    "id": "blog_post",
    "type": "ContentType",
    "createdAt": "2021-09-28T04:32:51.311Z",
    "updatedAt": "2022-01-13T21:44:49.144Z",
    "environment": {
      "sys": {
        "id": "master",
        "type": "Link",
        "linkType": "Environment"
      }
    },
    "publishedVersion": 5,
    "publishedAt": "2022-01-13T21:44:49.144Z",
    "firstPublishedAt": "2021-09-28T04:32:51.697Z",
    "createdBy": {
      "sys": {
        "type": "Link",
        "linkType": "User",
        "id": "5UYiZVG3lSpxwKxNcF1PJV"
      }
    },
    "updatedBy": {
      "sys": {
        "type": "Link",
        "linkType": "User",
        "id": "5UYiZVG3lSpxwKxNcF1PJV"
      }
    },
    "publishedCounter": 3,
    "version": 6,
    "publishedBy": {
      "sys": {
        "type": "Link",
        "linkType": "User",
        "id": "5UYiZVG3lSpxwKxNcF1PJV"
      }
    }
  }
}

**Comment by nmelhado** [comment]
I haven't been able to reproduce this locally yet. I'm going to convert this to a discussion for the time being
